-- NBA 90%ers Database Schema
-- Tracks scanner runs and individual picks across multiple sports

-- Scanner runs table (tracks each execution)
CREATE TABLE scanner_runs (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Run metadata
  sport TEXT NOT NULL,           -- 'nba' or 'nfl'
  scan_date DATE NOT NULL,       -- When the scan ran
  game_date DATE,                -- First game date for that day

  -- Stats
  total_picks INTEGER DEFAULT 0,
  players_analyzed INTEGER DEFAULT 0,
  players_skipped INTEGER DEFAULT 0,

  -- Performance (calculated later when results come in)
  picks_hit INTEGER,
  picks_missed INTEGER,
  hit_rate DECIMAL,

  -- Execution info
  execution_time_seconds DECIMAL,
  error_message TEXT,

  -- Ensure one run per sport per scan date
  UNIQUE(sport, scan_date)
);

-- Individual picks table
CREATE TABLE picks (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  run_id BIGINT REFERENCES scanner_runs(id) ON DELETE CASCADE,

  -- Sport/date info
  sport TEXT NOT NULL,
  scan_date DATE NOT NULL,
  game_date DATE,

  -- Pick details
  player_name TEXT NOT NULL,
  stat_type TEXT NOT NULL,      -- PTS, REB, AST, FG3M, STL, BLK, etc.
  line DECIMAL NOT NULL,         -- Betting line
  floor DECIMAL NOT NULL,        -- 90%er floor
  avg DECIMAL NOT NULL,          -- Season average
  confidence TEXT NOT NULL,      -- Currently only 'HIGH', but flexible for future

  -- Calculated values
  lower_bound DECIMAL,
  upper_bound DECIMAL,

  -- Result tracking (filled in later)
  actual_result DECIMAL,
  hit BOOLEAN,

  -- Metadata
  season TEXT DEFAULT '2025-26'
);

-- Indexes for common queries
CREATE INDEX idx_picks_run ON picks(run_id);
CREATE INDEX idx_picks_sport_date ON picks(sport, scan_date);
CREATE INDEX idx_picks_player ON picks(player_name);
CREATE INDEX idx_picks_confidence ON picks(confidence);
CREATE INDEX idx_runs_sport_date ON scanner_runs(sport, scan_date);

-- Comments for documentation
COMMENT ON TABLE scanner_runs IS 'Tracks each scanner execution with aggregate stats';
COMMENT ON TABLE picks IS 'Individual picks generated by the scanner';
COMMENT ON COLUMN picks.floor IS '10th percentile - player hits this value in 90% of games';
COMMENT ON COLUMN picks.confidence IS 'HIGH = floor >= line';
